baseURL = "https://lintmx.com/"
languageCode = "zh"
title = "Otakone"
theme = "archie"
enableRobotsTXT = true
hasCJKLanguage = true
disableKinds = ["taxonomyTerm"]
copyright = "© Leo Stock"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[mediaTypes]
    [mediaTypes."application/atom"]
        suffixes = ["xml"]
    [mediaTypes."application/rss"]
        suffixes = ["xml"]

[outputFormats]
    [outputFormats.Atom]
        mediaType = "application/atom"
        baseName = "atom"
    [outputFormats.Rss]
        mediaType = "application/rss"
        baseName = "feed"

[outputs]
    home = ["HTML", "Atom", "Rss"]
    page = ["HTML"]
    section = ["HTML"]
    taxonomy = ["HTML"]

[params]
	mode="auto" # color-mode → light,dark or auto
	featherIconsCDN=true

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/lintmx"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/lintmx"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3